// Code generated by foobar DO NOT EDIT!!

// Package p20161207 is sample for https://qiita.com/items/0d9f70d9970ae086f0ce
package p20161207

import "fmt"

// GeneratedFunc is sample func
func GeneratedFunc() {
	fmt.Println("Hello world")
}
